# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - test.mockup
        - filebeat
  pillars:
    top.sls:
      base:
        "*":
          - filebeat

platforms:
  - name: debian_jessie

suites:
  - name: default
    provisioner:
      pillars:
        filebeat.sls:
          filebeat:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        filebeat.sls: pillar-custom.sls
